# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f6628e980dc66a39b5e499c67f7723e4"
name = "DDKT Analysis Tracking"
handle = "ddkt-analysis-tracking"
application_url = "https://shopify-ddkt-analysis-tracking.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_script_tags,read_script_tags"

[auth]
redirect_urls = [
  "https://shopify-ddkt-analysis-tracking.vercel.app/auth/callback",
  "https://shopify-ddkt-analysis-tracking.vercel.app/auth/shopify/callback",
  "https://shopify-ddkt-analysis-tracking.vercel.app/api/auth/callback"
]

[pos]
embedded = false
